# Generated by Django 5.1.4 on 2024-12-10 15:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('animal_name', models.CharField(max_length=150, verbose_name='Имя животного')),
                ('species', models.CharField(max_length=150, verbose_name='Вид животного')),
                ('test_date', models.DateField(verbose_name='Дата проведения теста')),
                ('milk_yield', models.FloatField(validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Продуктивность')),
                ('health_status', models.CharField(choices=[('good', 'хорошее'), ('poor', 'плохое')], max_length=150, verbose_name='Состояние здоровья')),
            ],
        ),
    ]
