# Generated by Django 5.1.4 on 2024-12-11 06:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animal_api', '0003_alter_genetictest_health_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genetictest',
            name='milk_yield',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Продуктивность'),
        ),
    ]
